import './bootstrap';
import './menuModal';
import './responsesSlider';
import './categoriesSlider';
import './cartModal';
import './bannerSlider';
import './popularProductSlider';
import './productPreviewSlider';
import './filterModal';