import './bootstrap';
import './menuModal';
import './responsesSlider';
import './categoriesSlider';
import './cartModal';
import './bannerSlider';
import './popularProductSlider';
import './productPreviewSlider';
import './filterModal';
import './oneClickModal';
import './successModal';
import "./quiz.js";
import "./noUISlider.js"
import "./pagination.js";
import "./feedback.js"
import "./counter.js"