<?php

namespace App\Http\Controllers;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class NavController extends Controller
{
    public $products = [
        ["id" => 1, "img" => ["product.svg", "product.svg", "product.svg"], "name" => "Дріт монтажний 24AWG (0,2 мм2), 10 см, 1BLK02-2STT-10-2STT, чорний, PVC,  упаковка 100 шт", "price" => 0, 'popular' => true, 'inStock' => true, 'countInPackage' => 100, 'discount' => 35, 'art' => 111222, 'characteristics' => ['Довжина' => '0,5–10 мм', 'Колір' => 'Червоний', 'Ізоляція' => 'Силікон', 'Перетин' => '0,032 мм² / AWG32', 'Тип жили' => 'Луджена багатожильна', 'Обробка' => 'Зачистка'], 'description' => 'Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?'],
        ["id" => 2, "img" => ["product.svg", "product.svg", "product.svg"], "name" => "Дріт монтажний 24AWG (0,2 мм2), 10 см, 1BLK02-2STT-10-2STT, чорний, PVC,  упаковка 100 шт", "price" => 0, 'popular' => true, 'inStock' => true, 'countInPackage' => 100, 'discount' => 10, 'art' => 111222, 'characteristics' => ['Довжина' => '0,5–10 мм', 'Колір' => 'Червоний', 'Ізоляція' => 'Силікон', 'Перетин' => '0,032 мм² / AWG32', 'Тип жили' => 'Луджена багатожильна', 'Обробка' => 'Зачистка'], 'description' => 'Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?'],
        ["id" => 3, "img" => ["product.svg", "product.svg", "product.svg"], "name" => "Дріт монтажний 24AWG (0,2 мм2), 10 см, 1BLK02-2STT-10-2STT, чорний, PVC,  упаковка 100 шт", "price" => 0, 'popular' => true, 'inStock' => true, 'countInPackage' => 100, 'discount' => 10, 'art' => 111222, 'characteristics' => ['Довжина' => '0,5–10 мм', 'Колір' => 'Червоний', 'Ізоляція' => 'Силікон', 'Перетин' => '0,032 мм² / AWG32', 'Тип жили' => 'Луджена багатожильна', 'Обробка' => 'Зачистка'], 'description' => 'Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?'],
        ["id" => 4, "img" => ["product.svg", "product.svg", "product.svg"], "name" => "Дріт монтажний 24AWG (0,2 мм2), 10 см, 1BLK02-2STT-10-2STT, чорний, PVC,  упаковка 100 шт", "price" => 0, 'popular' => true, 'inStock' => true, 'countInPackage' => 100, 'discount' => 10, 'art' => 111222, 'characteristics' => ['Довжина' => '0,5–10 мм', 'Колір' => 'Червоний', 'Ізоляція' => 'Силікон', 'Перетин' => '0,032 мм² / AWG32', 'Тип жили' => 'Луджена багатожильна', 'Обробка' => 'Зачистка'], 'description' => 'Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?'],
        ["id" => 5, "img" => ["product.svg", "product.svg", "product.svg"], "name" => "Дріт монтажний 24AWG (0,2 мм2), 10 см, 1BLK02-2STT-10-2STT, чорний, PVC,  упаковка 100 шт", "price" => 0, 'popular' => true, 'inStock' => true, 'countInPackage' => 100, 'discount' => 10, 'art' => 111222, 'characteristics' => ['Довжина' => '0,5–10 мм', 'Колір' => 'Червоний', 'Ізоляція' => 'Силікон', 'Перетин' => '0,032 мм² / AWG32', 'Тип жили' => 'Луджена багатожильна', 'Обробка' => 'Зачистка'], 'description' => 'Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?'],
        ["id" => 6, "img" => ["product.svg", "product.svg", "product.svg"], "name" => "Дріт монтажний 24AWG (0,2 мм2), 10 см, 1BLK02-2STT-10-2STT, чорний, PVC,  упаковка 100 шт", "price" => 0, 'popular' => true, 'inStock' => true, 'countInPackage' => 100, 'discount' => 10, 'art' => 111222, 'characteristics' => ['Довжина' => '0,5–10 мм', 'Колір' => 'Червоний', 'Ізоляція' => 'Силікон', 'Перетин' => '0,032 мм² / AWG32', 'Тип жили' => 'Луджена багатожильна', 'Обробка' => 'Зачистка'], 'description' => 'Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?'],
        ["id" => 7, "img" => ["product.svg", "product.svg", "product.svg"], "name" => "Дріт монтажний 24AWG (0,2 мм2), 10 см, 1BLK02-2STT-10-2STT, чорний, PVC,  упаковка 100 шт", "price" => 0, 'popular' => true, 'inStock' => true, 'countInPackage' => 100, 'discount' => 10, 'art' => 111222, 'characteristics' => ['Довжина' => '0,5–10 мм', 'Колір' => 'Червоний', 'Ізоляція' => 'Силікон', 'Перетин' => '0,032 мм² / AWG32', 'Тип жили' => 'Луджена багатожильна', 'Обробка' => 'Зачистка'], 'description' => 'Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?'],
        ["id" => 8, "img" => ["product.svg", "product.svg", "product.svg"], "name" => "Дріт монтажний 24AWG (0,2 мм2), 10 см, 1BLK02-2STT-10-2STT, чорний, PVC,  упаковка 100 шт", "price" => 0, 'popular' => true, 'inStock' => true, 'countInPackage' => 100, 'discount' => 10, 'art' => 111222, 'characteristics' => ['Довжина' => '0,5–10 мм', 'Колір' => 'Червоний', 'Ізоляція' => 'Силікон', 'Перетин' => '0,032 мм² / AWG32', 'Тип жили' => 'Луджена багатожильна', 'Обробка' => 'Зачистка'], 'description' => 'Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?'],
        ["id" => 9, "img" => ["product.svg", "product.svg", "product.svg"], "name" => "Дріт монтажний 24AWG (0,2 мм2), 10 см, 1BLK02-2STT-10-2STT, чорний, PVC,  упаковка 100 шт", "price" => 0, 'popular' => true, 'inStock' => true, 'countInPackage' => 100, 'discount' => 35, 'art' => 111222, 'characteristics' => ['Довжина' => '0,5–10 мм', 'Колір' => 'Червоний', 'Ізоляція' => 'Силікон', 'Перетин' => '0,032 мм² / AWG32', 'Тип жили' => 'Луджена багатожильна', 'Обробка' => 'Зачистка'], 'description' => 'Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?'],
        ["id" => 10, "img" => ["product.svg", "product.svg", "product.svg"], "name" => "Дріт монтажний 24AWG (0,2 мм2), 10 см, 1BLK02-2STT-10-2STT, чорний, PVC,  упаковка 100 шт", "price" => 0, 'popular' => true, 'inStock' => true, 'countInPackage' => 100, 'discount' => 10, 'art' => 111222, 'characteristics' => ['Довжина' => '0,5–10 мм', 'Колір' => 'Червоний', 'Ізоляція' => 'Силікон', 'Перетин' => '0,032 мм² / AWG32', 'Тип жили' => 'Луджена багатожильна', 'Обробка' => 'Зачистка'], 'description' => 'Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?'],
        ["id" => 11, "img" => ["product.svg", "product.svg", "product.svg"], "name" => "Дріт монтажний 24AWG (0,2 мм2), 10 см, 1BLK02-2STT-10-2STT, чорний, PVC,  упаковка 100 шт", "price" => 0, 'popular' => true, 'inStock' => true, 'countInPackage' => 100, 'discount' => 10, 'art' => 111222, 'characteristics' => ['Довжина' => '0,5–10 мм', 'Колір' => 'Червоний', 'Ізоляція' => 'Силікон', 'Перетин' => '0,032 мм² / AWG32', 'Тип жили' => 'Луджена багатожильна', 'Обробка' => 'Зачистка'], 'description' => 'Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?'],
        ["id" => 12, "img" => ["product.svg", "product.svg", "product.svg"], "name" => "Дріт монтажний 24AWG (0,2 мм2), 10 см, 1BLK02-2STT-10-2STT, чорний, PVC,  упаковка 100 шт", "price" => 0, 'popular' => true, 'inStock' => true, 'countInPackage' => 100, 'discount' => 10, 'art' => 111222, 'characteristics' => ['Довжина' => '0,5–10 мм', 'Колір' => 'Червоний', 'Ізоляція' => 'Силікон', 'Перетин' => '0,032 мм² / AWG32', 'Тип жили' => 'Луджена багатожильна', 'Обробка' => 'Зачистка'], 'description' => 'Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?'],
        ["id" => 13, "img" => ["product.svg", "product.svg", "product.svg"], "name" => "Дріт монтажний 24AWG (0,2 мм2), 10 см, 1BLK02-2STT-10-2STT, чорний, PVC,  упаковка 100 шт", "price" => 0, 'popular' => true, 'inStock' => true, 'countInPackage' => 100, 'discount' => 10, 'art' => 111222, 'characteristics' => ['Довжина' => '0,5–10 мм', 'Колір' => 'Червоний', 'Ізоляція' => 'Силікон', 'Перетин' => '0,032 мм² / AWG32', 'Тип жили' => 'Луджена багатожильна', 'Обробка' => 'Зачистка'], 'description' => 'Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?'],
        ["id" => 14, "img" => ["product.svg", "product.svg", "product.svg"], "name" => "Дріт монтажний 24AWG (0,2 мм2), 10 см, 1BLK02-2STT-10-2STT, чорний, PVC,  упаковка 100 шт", "price" => 0, 'popular' => true, 'inStock' => true, 'countInPackage' => 100, 'discount' => 10, 'art' => 111222, 'characteristics' => ['Довжина' => '0,5–10 мм', 'Колір' => 'Червоний', 'Ізоляція' => 'Силікон', 'Перетин' => '0,032 мм² / AWG32', 'Тип жили' => 'Луджена багатожильна', 'Обробка' => 'Зачистка'], 'description' => 'Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?'],
        ["id" => 15, "img" => ["product.svg", "product.svg", "product.svg"], "name" => "Дріт монтажний 24AWG (0,2 мм2), 10 см, 1BLK02-2STT-10-2STT, чорний, PVC,  упаковка 100 шт", "price" => 0, 'popular' => true, 'inStock' => true, 'countInPackage' => 100, 'discount' => 10, 'art' => 111222, 'characteristics' => ['Довжина' => '0,5–10 мм', 'Колір' => 'Червоний', 'Ізоляція' => 'Силікон', 'Перетин' => '0,032 мм² / AWG32', 'Тип жили' => 'Луджена багатожильна', 'Обробка' => 'Зачистка'], 'description' => 'Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?'],
        ["id" => 16, "img" => ["product.svg", "product.svg", "product.svg"], "name" => "Дріт монтажний 24AWG (0,2 мм2), 10 см, 1BLK02-2STT-10-2STT, чорний, PVC,  упаковка 100 шт", "price" => 0, 'popular' => true, 'inStock' => true, 'countInPackage' => 100, 'discount' => 10, 'art' => 111222, 'characteristics' => ['Довжина' => '0,5–10 мм', 'Колір' => 'Червоний', 'Ізоляція' => 'Силікон', 'Перетин' => '0,032 мм² / AWG32', 'Тип жили' => 'Луджена багатожильна', 'Обробка' => 'Зачистка'], 'description' => 'Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?'],
    ];
    public $cartProducts = [];

    public function getHomePage()
    {
        $products = $this->products;
        return view("pages.homePage", compact("products"));
    }
    public function getProductPage($productId)
    {
        $products = $this->products;

        $chooseProduct = collect($products)->filter(function ($product) use ($productId) {
            return $product['id'] == $productId;
        });
        $product = $chooseProduct->first();
        return view('pages.productPage', compact('chooseProduct', 'products'));
    }
}
